title: MLQuickStudySheets
author: André Ramolivaz
logo: logo.png


execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex



repository:
  url: https://github.com/andreramolivaz/MLQuickStudySheets
  path_to_book: https://github.com/andreramolivaz/MLQuickStudySheets/tree/main/book
  branch: main  


html:
  use_issues_button: true
  use_repository_button: true
